default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-typing-imports==1.10.1"]
        args:
          - "--max-complexity=10"
          - "--max-line-length=88"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.812
  #   hooks:
  #     - id: mypy
