name: Tests

on: [push]

jobs:
  build:
    name: "Unit Tests for python ${{ matrix.python }} on ${{ matrix.os }}"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction

      - name: Run Unit Tests
        run: |
          pytest --doctest-modules --cov=flask_firebase_admin --cov-report=xml --cov-report=term tests/ flask_firebase_admin/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
